version: '3'
services:

    postgres11:
        image: postgres:11.5
        container_name: postgres11
        environment:
            - PGPORT=5433
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
        ports:
            - "5433:5433"
        volumes:
            - ./volumes/pg_data:/var/lib/postgresql/data